language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - rbx

os:
  - linux
  - osx

branches:
  only:
    - master

gemfile:
  - Gemfile
  - Gemfile.cool.io.1.1.1

script: bundle exec rake

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
